[package]
name = "playit-agent-core"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
tokio = { version = "1.20", features = ["full"] }
playit-agent-common = { path = "../agent_common" }
serde = "1"
serde_json = "1"
rand = "0.8.5"
hyper = { version = "0.14.20", features = ["client", "http2", "http1"] }
hyper-rustls = { version = "0.23.0", features = ["webpki-tokio", "http2"] }
hex = "0.4.3"
toml = "0.5.9"
byteorder = "1.4.3"
