[package]
name = "playit-agent-common"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["use-hmac"]
use-ring = ["ring"]
use-hmac = ["hmac", "sha2"]
use-schema = ["schemars"]

[dependencies]
serde = { version = "1", features = ["derive"] }
bincode = "1.3.3"
byteorder = "1.4.3"
schemars = { version = "0.8.8", features = ["uuid", "chrono"], optional = true }
uuid = { version = "0.8.2", features = ["serde"] }
chrono = { version = "0.4.19", features = ["serde"] }
ring = { version = "0.16.20", optional = true }
hmac = { version = "0.12.1", optional = true }
sha2 = { version = "0.10.2", optional = true }

[dev-dependencies]
hex = "0.4.3"
serde_json = "1"