[package]
name = "playit-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
playit-agent-core = { path = "../agent_core" }
clap = { version = "4.0.10", features = ["derive"] }
rand = "0.8.5"
hex = "0.4.3"
anyhow = "1.0"
urlencoding = "2.1.2"
serde_json = "1"
uuid = "1.1.2"
