[package]
name = "playit-agent-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
byteorder = "1.4.3"
sha2 = "0.10.2"
hmac = "0.12.1"

[dev-dependencies]
rand = "0.8.5"